config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :categories
  
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
    validates :title, presence: true
    enum category_type: {
        "General" => 0,
        "News" => 1,
        "Sports" => 2
      }
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :category, :optional => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    @categories = Category.all
  end
  def show
    @category = Category.find(params[:id])
  end
  def new
    @category = Category.new
  end
  def create
    @category = Category.new(categories_params)

    if @category.save
      redirect_to @category
    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit
    @category= Category.find(params[:id])
  end
  def update
    @category = Category.find(params[:id])

    if @category.update(categories_params)
      redirect_to @category
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path, status: :see_other
  end
  private
    def categories_params
      params.require(:category).permit(:title, :description, :category_type)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :kind, :author, :category_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>
  <div class="text-center">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% category.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="text-center">
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% category.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div class="text-center">
    <%= form.label :category_type %><br>
    <%= form.select :category_type,Category.category_types.keys %>
    <% category.errors.full_messages_for(:types).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="text-center " style="margin-top:30px;">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="alert alert-info text-center" role="alert">
<h1>Edit Category</h1>
</div>
<%= render "form", category: @category %>
<div class="text-center" style="margin-top:50px;">
<button type="button" class="btn btn-outline-primary" ><%= link_to "Back ", categories_path %></button>

</div>

app/views/categories/index.html.erb
<div class="alert alert-info text-center" role="alert">
<h1>Category</h1>
</div>
<div class="text-center" style="margin-top:50px;margin-bottom:50px;">
<button type="button" class="btn btn-outline-primary" ><%= link_to "New category", new_category_path %></button>
<button type="button" class="btn btn-outline-success"><%= link_to "Back to home", root_path %></button>
</div>
<table class="table container">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Types</th>
    </tr>
  </thead>
  <% @categories.each do |category| %>
  <tbody>
  
    <tr>
    
      
      <td><%= link_to category.title, category %></td>
      <td><%=  category.description%></td>
      <td><%=  category.category_type%></td>
    </tr>
    
  </tbody>
  <% end %>
</table>

app/views/categories/new.html.erb
<div class="alert alert-info text-center" role="alert">
<h1>Add new Category</h1>
</div>
<%= render "form", category: @category %>
<div class="text-center" style="margin-top:50px;">
<button type="button" class="btn btn-outline-primary" ><%= link_to "Back ", categories_path %></button>

</div>

app/views/categories/show.html.erb
<div class="alert alert-info text-center" role="alert">
<h1>Show</h1>
</div>
<div class="card text-center" style="width: 18rem; margin:0 auto">
  <img src="https://kinsta.com/wp-content/uploads/2022/08/wordpress-wiki.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Title</h5>
    <p class="card-text"><%= @category.title %></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Description: <%= @category.description %></li>
    <li class="list-group-item">Category type: <%= @category.category_type %></li>
   
  </ul>
  <div class="card-body">
  <%= link_to "Edit", edit_category_path(@category) %>
  <%= link_to "Back ", categories_path %>
  <%= button_to "Destroy",@category, method: 'delete', data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wikiapplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red" class="text-center">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-center">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div class="text-center">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div class="text-center">
    <%= form.label :kind, style: "display: block" %>
    <%= form.text_area :kind %>
  </div>

  <div class="text-center">
    <%= form.label :author, style: "display: block" %>
    <%= form.text_area :author %>
  </div>
  <div class="text-center">
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category_id, Category.all.map {|c| [c.title, c.id]}  %>
  </div>

  <div class="text-center" style="margin-top:20px;">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="card text-center" style="width: 18rem; margin:0 auto">
<img src="https://kinsta.com/wp-content/uploads/2022/08/wordpress-wiki.jpg" class="card-img-top" alt="...">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= post.description %>
  </p>

  <p>
    <strong>Kind:</strong>
    <%= post.kind %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= post.author %>
  </p>
  <p>
    <strong>Category:</strong>
    <%= post.category && post.category.title %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div class="text-center">
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
<div class="row align-items-start">
    <div class="col-8">
    <h1>Posts</h1>
    </div>
    <div class="col-2">
    <button type="button" class="btn btn-outline-primary float-end"><%= link_to "New post", new_post_path %></button>
    </div>
    <div class="col-2">
    <button type="button" class="btn btn-outline-success"><%= link_to "Back to home", root_path %></button>
    </div>

</div>
<table class="table table-striped">
<thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Kind</th>
    <th>Author</th>
    <th colspan="2" class="text-center">Action</th>
  </tr>
  </thead>
  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.description %></td>
      <td><%= post.kind %></td>
      <td><%= post.author %></td>
      <td><%= link_to 'Show', post %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
    </tr>
  <% end %>
  </tbody>
  </table>
  </div>

app/views/posts/new.html.erb
<div class="alert alert-info text-center" role="alert">
<h1>Add new Post</h1>
</div>
<%= render "form", post: @post %>

<div class="text-center" style="margin-top:10px;">
<button type="button" class="btn btn-outline-primary" ><%= link_to "Back to posts", posts_path %></button>

</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="alert alert-info text-center" role="alert">
<h1>Post</h1>
</div>
<%= render @post %>

<div class="text-center">
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/welcome/index.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">WIKI APPLICATION</a>
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>
<h1 class="text-center link-info"><b>Chào mọi người đến với wiki app</b></h1>

<p class="text-center link-primary">Của Dương Văn Bi</p>
<div class="text-center">
<div class="spinner-grow text-primary" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-grow text-secondary" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-grow text-success" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-grow text-danger" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-grow text-warning" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-grow text-info" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-grow text-light" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-grow text-dark" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
</div>
<div class="text-center" >
  <img style="height:200px"src="https://herothemes.com/wp-content/uploads/1095319_Featured-image-graphic-for-HeroThemes_Op1_062221-880x495.png" class="rounded" alt="...">
</div>

<div class="text-center" style="margin-top:50px;">
<button type="button" class="btn btn-outline-primary" ><%= link_to "Vào POST nào", controller: "posts" %></button>
<button type="button" class="btn btn-outline-success"><%= link_to "Category", controller: "categories" %></button>
</div>